### ISSUE TITLE
Testnet V6 chainside CheckList

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#185]
Pull Requests: 
 

- [x]  evmos upgrade to v16 (https://github.com/ExocoreNetwork/exocore/pull/172)

- [x]  feat(precompile): Precompile for native restaking https://github.com/ExocoreNetwork/exocore/pull/195

- [x] feat(oracle): provide balance change of native-restaking asset
https://github.com/ExocoreNetwork/exocore/pull/189

- [x] feat(native restaking): add a function to update the states of native token restaking
https://github.com/ExocoreNetwork/exocore/pull/183

- [x]  feat:register vesting type, add support for delegation/undelegation of native token https://github.com/ExocoreNetwork/exocore/pull/127 

- [x]  feat(genesis export): genesis exporting for assets, delegation and operator modules
https://github.com/ExocoreNetwork/exocore/pull/108 

- [x]  feat(distribution): add fee-distribution and avs-reward distribution
https://github.com/ExocoreNetwork/exocore/pull/117 

- [x] feat(avs):Implement on-chain aggregation signature
https://github.com/ExocoreNetwork/exocore/pull/167 

Issue to be fixed: 

- [x] Operator USD is 0 at the end of first Epoch When Starting
 https://github.com/ExocoreNetwork/exocore/issues/177

- [x] AVS Register and AssociatewithEVMStaker Print Multiple ERR Logs even it succeed in the end
https://github.com/ExocoreNetwork/exocore/issues/168

- [x] feat(assets): remove total supply https://github.com/ExocoreNetwork/exocore/pull/181

Exocore-contract:

- [x] https://github.com/ExocoreNetwork/exocore-contracts/pull/93
- [x] https://github.com/ExocoreNetwork/exocore-contracts/pull/96

**Comment by MaxMustermann2** [comment]
Either both https://github.com/ExocoreNetwork/exocore/pull/181 and https://github.com/ExocoreNetwork/exocore-contracts/pull/93 should be included or none should be. If we intend to upgrade the contracts in v6, both will have to be included.

**Comment by cloud8little** [comment]
> Either both #181 and [ExocoreNetwork/exocore-contracts#93](https://github.com/ExocoreNetwork/exocore-contracts/pull/93) should be included or none should be. If we intend to upgrade the contracts in v6, both will have to be included.

Updated.
